version: '4.44.2'

networks:
  vm-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgres:
    container_name: vacancy-management-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vacancy_management
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - vm-network
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - vm-network
    ports:
      - "3000:3000"