version: '4.44.2'

services:
  postgres:
    container_name: vacancy-management-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vacancy_management